"""empty message

Revision ID: 68698b4739e2
Revises: f117a7d7a7f3
Create Date: 2022-06-04 18:27:04.046803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68698b4739e2'
down_revision = 'f117a7d7a7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=1028),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1028),
               existing_nullable=True)
    # ### end Alembic commands ###
