"""empty message

Revision ID: 993bd599004d
Revises: dbc3d9c66c01
Create Date: 2022-05-28 21:12:22.306946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993bd599004d'
down_revision = 'dbc3d9c66c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=1028), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
